name: SQLite FDW test

on:
  workflow_dispatch:
  pull_request:  
  #push:
    #branches:
      #- master
      #- main
jobs:
  test:
    env:
      SQLITE_VERSION : "3420000"
      SQLITE_YEAR: "2023"
    strategy:
      fail-fast: false
      matrix:
        pg: ["16.0","15.3","14.8","13.11","12.15"]
        
    name: Test on PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: install locales
        run: bash GitHubActions/install_locales.sh
      
      - name: build PostgreSQL ${{ matrix.pg }}
        run: bash GitHubActions/build_postgres.sh ${{ matrix.pg }}
      
      - name: install SQLite
        run: bash GitHubActions/install_sqlite.sh ${{ env.SQLITE_VERSION }} ${{ env.SQLITE_YEAR }}
      
      - name: build sqlite_fdw
        run: bash GitHubActions/build_sqlite_fdw.sh ${{ matrix.pg }}
      
      - name: execute sqlite_fdw test
        run: bash GitHubActions/execute_test.sh ${{ matrix.pg }} 
